dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

script:
  - coverage run --source hotxlfp setup.py test

after_success:
  - coverage combine
  - codecov
